name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build SvelteKit app
        run: npm run build
        
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token for publishing
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Release the app automatically
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          # Use our custom electron-builder config file
          args: "--config electron-builder.config.js"